// List of all static phrases used on the site
// No hardcoded strings are used in template files
// so that the whole template can be translated
// by editing just a handful of files (mostly this one :))

module.exports = {
  main_page: '首页',
  skip_to_main_content: '跳转到正文',
  disclaimer: '作者希望提醒',
  keep_reading: '继续阅读于',
  originally_published: '最初发布于',
  by: '作者',
  license: '许可协议',
  published: '发布于',
  page: '页',
  go_to_page: '输入（数字）',
  visit_website: '访问网站',
  tags: '标签',
  go: '跳转',
  newer: '较新',
  older: '较旧',
  articles: '篇文章',
  newer_article: '较新的文章',
  older_article: '较旧的文章',
  articles_tagged_as: '标签为',
  view_all_articles_tagged_as: '浏览标签为',
  tagged_as: '标签',
  copyright_symbol: '©',
  right_arrow_symbol: '→',
  left_arrow_symbol: '←',
  meta_separator: '•',
  feed: '订阅源',
  of: '/',
  min: '分钟',
  read: '阅读',
  words: '字',
  page_number_hint: '输入页码以快速跳转',
  feed_info: [
    '这是自动生成的 Atom / RSS 订阅源。如果您使用 RSS 阅读器，请使用此链接',
    '来订阅。',
  ],
  share_on: '分享到',
  share_this_article: '分享这篇文章',
  opens_prompt: '打开提示窗口',
  opens_new_tab: '在新标签页中打开',
  image_credit: '图片来源',
  copy_to_clipboard: '复制文章链接',
  which_instance: '分享到哪个实例？',
  mastodon_share_line_1:
    '点击分享将打开一个新的浏览器标签页。请确保您的浏览器允许网站打开新标签页。',
  mastodon_share_line_2:
    '您可以在发布前修改内容。',
  example: '示例',
  sample_instance: 'mastodon.social',
  close_window: '关闭此窗口',
  share: '分享',
};
